### ISSUE TITLE
Not working well for very first sync

### ISSUE THREAD

**Issue by BVerma-CRM** [SamKirkland/FTP-Deploy-Action#160]
First of all Thanks for the action, its very useful

But I did noticed few things, (not sure if I am missing something though).

**Issue#1** 
I have started using this action and expected it to sync all files from my repository to the FTP but is not doing for all files, it did created almost all folders but did not created files in all of them.
The action status is showing success though.

**Issue#2**
When I am modifying few files I was expected that it will only pick the modified files and sync them on FTP, but its syncing ALL files again which is an time taking action as my repository is having lots of files.

Please suggest.

**Comment by thide11** [comment]
This action is very good, but in certain cases its best create a .git on root of you project, and create an action to access you server via ssh and call `git pull`...

**Comment by RoccoCocco** [comment]
@thide11 Well, if I had access to `ssh` I wouldn't be using this action. Unfortunately few of shared hosting don't offer `ssh` on their basic plans, so we are either stuck with uploading files manually or using FTP sync.

**Comment by thide11** [comment]
You can create a secret route on you web appllication that make a git pull bash command on any backend programming language that is using

**Comment by RoccoCocco** [comment]
@thide11 From my experience, the server that doesn't offer `ssh`, usually has bash commands disabled/blacklisted for the language. See attached screenshot of disabled PHP functions in an legacy project that I'm maintaining. Notice that all function that are usually used for running bash commands are disabled (system, shell_exec, exec, ...).

![image](https://user-images.githubusercontent.com/70594433/113503083-ed2bbc00-952f-11eb-888f-fe96f6d89b19.png)

This is usually an issue when maintaining legacy PHP projects, since other tech stacks  I'm dealing with, run on a dedicated resources.

If you are aware of any other method, please let me know.
