### ISSUE TITLE
Questions on ftp-deploy-sync-state.json

### ISSUE THREAD

**Issue by ilonashairstyling** [SamKirkland/FTP-Deploy-Action#194]
In file .ftp-deploy-sync-state.json on destination FTP folder there are 2 attributes:
{
    "version": "1.0.0",
    "generatedTime": 1619618282691
}

Question:
 - When is version updated? On what is it based?
 - generatedTime - how can I get this to a readable date/time format?

**Comment by SamKirkland** [comment]
Hello,

The `version` property is used internally by this script. The `version` property will only change if this script has a update that breaks previous versions. The version is stored so users can be warned that they are on a old version. This has never happened before but it's a future-proofing measure.

The `generatedTime` property is a i[nteger that represents milliseconds since 1 January 1970 UTC](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date).
To convert this into a nicely formatted date (example in javascript)
```javascript
let lastDeployedDateTime = new Date(1619618282691);
console.log(lastDeployedDateTime.toLocaleString());

// This will output 4/28/2021, 8:58:02 AM
// Note: The exact format depends on the culture of the user
```
