### ISSUE TITLE
Delete files that are not in repo

### ISSUE THREAD

**Issue by NickDaelemans** [SamKirkland/FTP-Deploy-Action#241]
Is there a way to replace the entire content inside the server-dir? Right now, files that aren't in Git, but are on the server still exist after syncing the files. This means you're not able to delete any file using the action. Am I missing something?

**Comment by SamKirkland** [comment]
Correct. FTP has no fast way of doing this. I would have to enumerate every folder which takes a significant amount of time. This was a performance tradeoff I made to make deployments fast.

This action does have a opt-out `dangerous-clean-slate` which will delete the entire target dir before performing a sync, it's hard to believe but deleting & reuploading everything is actually faster than enumerating folders/files due to ftp lacking file hashes.

[See readme for more info.](https://github.com/SamKirkland/FTP-Deploy-Action#settings)

I'm going to close this issue out.
