### ISSUE TITLE
Sync files with several server

### ISSUE THREAD

**Issue by Andyt8** [SamKirkland/FTP-Deploy-Action#266]
Hello,

I tried to Sync files with one server and it was working successful. However, is it possible to extend the script for different server?

Example:

>on: push
>name: 🚀 Deploy website on push
>jobs:
>  web-deploy:
>    name: 🎉 Deploy
>    runs-on: ubuntu-latest
>    steps:
>    - name: 🚚 Get latest code
>      uses: actions/checkout@v2
>    
>    - name: 📂 Sync files A
>      uses: SamKirkland/FTP-Deploy-Action@4.2.0
>      with:
>        server: ${{ secrets.ftp_a_server }}
>        username: ${{ secrets.ftp_a_username }}
>        password: ${{ secrets.ftp_a_password }}
>        protocol: ftps
>
>    - name: 📂 Sync files B
>      uses: SamKirkland/FTP-Deploy-Action@4.2.0
>      with:
>        server: ${{ secrets.ftp_b_server }}
>        username: ${{ secrets.ftp_b_username }}
>        password: ${{ secrets.ftp_b_password }}
>        protocol: ftps

Would that work? Is it possible to extend that?

**Comment by Andyt8** [comment]
Hello,

There is an additional question. According to "Setup Steps" the name should be main.yml. Is it possible to use several yml files with different name like synca.yml and syncb.yml?

Trying around with sync to multiple FTP a bit, but don't know if it fundamentally can't work or if I have a mistake somewhere.

**Comment by SamKirkland** [comment]
Hey Andy!

You answered your own question!

Both of your ideas would work. However the main con with placing both publishes in a single yaml file is they will run synchronously (by default). Also if one failed the next would not run (by default).

If you want the deploys to happen in parallel define each in it's own `job` (note: untested code)
```yaml
jobs:
  checkoutCode:
    # checkout code here
  buildProject:
    # build project here
  deployA:
      needs: [checkoutCode, buildProject]
      # deploy on server 1
  deployB:
      needs: [checkoutCode, buildProject]
      # deploy on server 1
```

The other option as you pointed out would be multiple `yaml` files. Each `yaml` file will run it's own action. And you can name it whatever you want so long as it ends in `.yaml`!!
They will run in parallel, this is the approach I take for my projects. But you have a bit more overhead because you need to repeat the steps.

If you have lengthy prereqs like build steps, linting, running tests - place them in a single file and use jobs.
If you don't have a lot of prereqs you can use separate yaml files.


Closing this because I feel like I've answered your question. I can reopen as needed.

**Comment by Andyt8** [comment]
Thank you for your answer.
