### ISSUE TITLE
Blank lines on transfer files

### ISSUE THREAD

**Issue by GameStrikeBR** [SamKirkland/FTP-Deploy-Action#283]
Files are getting blank lines between lines in code on push, resulting in larger files. There is any config to ASCII to Binary file transfer option?

**Comment by SamKirkland** [comment]
I haven't seen this problem before, this library and it's dependency (basic-ftp) doesn't look at the contents of the file. It just uploads it.

I think your issue is probably due to DOS vs. Unix line separator differences. Are you writing code on windows and upload to a linux/mac? Or the other way around?
