### ISSUE TITLE
TLS insecure and other flags not working

### ISSUE THREAD

**Issue by danielloader** [SamKirkland/FTP-Deploy-Action#34]
Hello I'm trying to use some "set" commands on the runtime of lftp to ignore TLS issues on the remote destination (not under my control to actually fix the server)
Example:
```    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: src
        ARGS: "-e 'set ssl:verify-certificate false; set ftp:ssl-force true; set ftp:ssl-protect-data true'"
```

As expected this fails, how is best to pass this over? could I use an .lftprc file in the repo for example?

Thanks

**Comment by SamKirkland** [comment]
The script already includes `-e` so you can leave that out of your args.
I haven't tried using custom set options. This script will include your custom arguments within the lftp mirror command instead of before it, which might be the root of the issue.
Here is what the script will run: `mirror {customARGS} -R {source} {destination}`
This script doesn't have support for a .lftprc file.

I'm on mobile right now, let me know if passing in `set ssl:verify-certificate false; set ftp:ssl-force true; set ftp:ssl-protect-data true` (no quotes) resolves the issue.
