### ISSUE TITLE
Clear the folder before/after upload

### ISSUE THREAD

**Issue by thebspin** [SamKirkland/FTP-Deploy-Action#52]
I think this was possible in the past when you passed on the `--delete` arg? But this no longer seems to work and i can't find it back in the docs.

But when you build something with vue/react or any other js library as far as i know they give some files unique hashed names everytime. That means on every upload i'm having extra files i no longer need.

Is it possible to clear the folder before or preferably after? The later will need to see what files are new or changed and remove the rest i suppose. Where before will cause a small downtime.

**Comment by januszmarcinik** [comment]
Hi,
Try this action instead :)
It cleans destination folder first, each time when is executed.
https://github.com/marketplace/actions/deploy-app-by-ftp

**Comment by sdegetaus** [comment]
I am curious about this too

**Comment by SamKirkland** [comment]
Currently this library does not support deleting files unless those files exist in source control.
Like you said an older version of this library ([v2.0.0](https://github.com/marketplace/actions/ftp-deploy?version=2.0.0)) does this. You can use version 2.0.0 if you'd like. I'll look into re-adding this.

The only real disadvantage of v2 is the publish can take longer because it's not using git to determine what to publish (so it has to look at every file).

Also side-node some libraries delete all files **before** uploading starts. That's not an ideal solution because it causes downtime until the publish is complete.

Thanks.

**Comment by Zenoo** [comment]
Deleting files deleted in commits would be great, I have to manually do it in Filezilla right now, which defeats the whole point ...

**Comment by baba43** [comment]
That would be a very nice and important feature. 

Like @Zenoo said, this Action becomes useless if one has to clean up the target directory manually over time. 

However, I'm thankful for the effort you've put into this project so far.

**Comment by SamKirkland** [comment]
version 4 will now sync all changes by default! woohoo!
