### ISSUE TITLE
Remove remote content before transferring files

### ISSUE THREAD

**Issue by Mdelaf** [SamKirkland/FTP-Deploy-Action#89]
Every time I build my Angular app, the generated files have a different names because their names contains a hash generated by Angular.

The problem with this is that on every deploy, more and more files accumulate on the server and they never get deleted nor replaced. 

I'd like to empty the remote destination folder before uploading the new files on each deployment, is that possible with this action?

**Comment by SamKirkland** [comment]
Hey Martin,

Currently this library does not support deleting files unless those files exist in source control.
An older version of this library ([v2.0.0](https://github.com/marketplace/actions/ftp-deploy?version=2.0.0)) does this. You can use version 2.0.0 if you'd like.

The only real disadvantage is the publish can take longer because it's not using git to determine what to publish (so it has to look at every file).

Thanks.
